### ISSUE TITLE
wavTranscriber - IndexError: list index out of range

### ISSUE THREAD

**Issue by IvanLjubicic** [terry-yip/speech-to-text#1]
Hi @terry-yip 

I have one question if you dont mind.

When I run your app with 

`python3 speech_to_text.py --audio=wavs/test2.wav`

i get error:

```
DEBUG:__main__:Processing speech recognition
Traceback (most recent call last):
  File "speech_to_text.py", line 69, in <module>
    main(sys.argv[1:])
  File "speech_to_text.py", line 35, in main
    output_graph, alphabet, lm, trie = wavTranscriber.resolve_models(model_path)
  File "/home/ivan/PycharmProjects/speech-to-text/wavTranscriber.py", line 77, in resolve_models
    pb = glob.glob(dirName + "/*.pb")[0]
IndexError: list index out of range
```
Can you please tell me if you can point where is the problem in this case?

I run this code on Ubuntu.

nice work btw!

EDIT: I have solved this step.
Can you please provide what versions of deepspeech, tensorflow etc. you used?

**Comment by terry-yip** [comment]
Thanks for leaving message and glad to hear you resolved this step. 
Following were the packages installed on my venv when I developed this project. Hope it's helpful.
absl-py              0.7.1      
astor                0.8.0      
astroid              2.4.2      
audioread            2.1.8      
cffi                 1.12.3     
decorator            4.4.0      
deepspeech           0.5.1      
gast                 0.2.2      
google-pasta         0.1.7      
grpcio               1.22.0     
h5py                 2.9.0      
isort                5.6.4      
joblib               0.13.2     
Keras                2.2.4      
Keras-Applications   1.0.8      
Keras-Preprocessing  1.1.0      
lazy-object-proxy    1.4.3      
librosa              0.7.0      
llvmlite             0.29.0     
Markdown             3.1.1      
mccabe               0.6.1      
numba                0.45.0     
numpy                1.16.4     
pip                  19.2       
protobuf             3.9.0      
PyAudio              0.2.11     
pycparser            2.19       
pylint               2.6.0      
PyYAML               5.1.1      
resampy              0.2.1      
scikit-learn         0.21.2     
scipy                1.3.0      
setuptools           41.0.1     
six                  1.12.0     
SoundFile            0.10.2     
tensorboard          1.14.0     
tensorflow           1.14.0     
tensorflow-estimator 1.14.0     
termcolor            1.1.0      
toml                 0.10.1     
torch                1.1.0.post2
typed-ast            1.4.1      
webrtcvad            2.0.10     
Werkzeug             0.15.5     
wheel                0.33.4     
wrapt                1.11.2

**Comment by terry-yip** [comment]
@IvanLjubicic I suppose you already resolved this issue. I'll close this if you don't have further question.
