### ISSUE TITLE
alphabet = glob.glob(dirName + "/alphabet.txt")[0] IndexError: list index out of range

### ISSUE THREAD

**Issue by Jaswanth-Devarinti** [terry-yip/speech-to-text#4]
DEBUG:speaker_diarization:[Speaker diarization] Clustering utterance features
DEBUG:speaker_diarization:[Speaker diarization] Tagging segments speakers
DEBUG:__main__:Processing speech recognition
Traceback (most recent call last):
  File "/content/speech-to-text/speech_to_text.py", line 69, in <module>
    main(sys.argv[1:])
  File "/content/speech-to-text/speech_to_text.py", line 35, in main
    output_graph, alphabet, lm, trie = wavTranscriber.resolve_models(model_path)
  File "/content/speech-to-text/wavTranscriber.py", line 80, in resolve_models
    alphabet = glob.glob(dirName + "/alphabet.txt")[0]
IndexError: list index out of range

Please resolve this issue.

**Comment by terry-yip** [comment]
As DeepSpeech pre-trained English model is too big to commit to git. You could download from (https://github.com/mozilla/DeepSpeech/releases/download/v0.6.1/deepspeech-0.6.1-models.tar.gz)

Please put the downloaded model files into folder speech-to-text/deepspeech/models
