### ISSUE TITLE
class VladPooling(keras.engine.Layer): AttributeError: module 'keras.engine' has no attribute 'Layer

### ISSUE THREAD

**Issue by Arwiin07** [terry-yip/speech-to-text#5]
Pls Help me for solving this issue

**Comment by Arwiin07** [comment]
class VladPooling(keras.engine.Layer):
AttributeError: module 'keras.engine' has no attribute 'Layer

**Comment by terry-yip** [comment]
I think it's the version mismatch, please try the version listed in readme
